config/routes.rb
Rails.application.routes.draw do
  
  resources :conferences
  resources :parents
  resources :teachers, except: [:index] do
    resources :students
  end
  resources :courses

  get '/' => 'welcome#home'
  get '/signup' => 'teachers#new'
  post '/signup' => 'teachers#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/students/:id/enroll' => 'students#enroll', as: 'enroll'
  post '/students/:id/enroll' => 'students#create_enrollment'
  get '/students/:id/unenroll' => 'students#unenroll', as: 'unenroll'
end

app/models/student.rb
class Student < ApplicationRecord
    validates :name, presence: true
    belongs_to :teacher
    belongs_to :parent, dependent: :destroy
    has_many :course_student, dependent: :nullify
    has_many :courses, through: :course_student   
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
layout "logged_in"

    before_action :authenticate

    def index
        if params[:teacher_id]      
            @teacher = Teacher.find(params[:teacher_id])
            if @teacher
              @students = @teacher.students
            elsif !@teacher
              redirect_to teachers_path
            end
        else
            @students = Student.all
        end
    end

    def new
      @teacher = Teacher.find(params[:teacher_id])
      @student = Student.new
    end

    def create
      @teacher = Teacher.find(params[:teacher_id])
      @student = Student.create(student_params)
      @student.teacher = @teacher
      #@parent = Parent.create(parent_params)
      @parent = Parent.create(name: params[:student][:parent_name], phone: params[:student][:parent_phone], email: params[:student][:parent_email])
      if @parent.save
        @student.parent = @parent
        @student.save
        redirect_to teacher_student_path(@teacher, @student)
      else
        render :new
      end
    end

    def show
        @student = Student.find(params[:id])
        @teacher = Teacher.find(params[:teacher_id])
        @courses = @teacher.courses
        authorize(@student)          
        if !@student
          redirect_to teacher_students_path
        end
    end

    def edit
      @student = Student.find(params[:id])
      @teacher = Teacher.find(params[:teacher_id])
      authorize(@student)          
    end

    def update
      @student = Student.find(params[:id])
      @teacher = Teacher.find(params[:teacher_id])
      authorize(@student)          
      @student.update(student_params)
      render :show
    end

    def destroy
      @student = Student.find(params[:id])
      @student.destroy
      redirect_to teacher_students_path
    end

    private 

    def student_params
      params.require(:student).permit(:name, :bio, :strengths, 
                                    :weaknesses, :interests, :grades, course_ids: [])
    end

    # def parent_params
    #   params.require(:student).permit(:parent_name, :parent_phone, :parent_email) 
    # end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/edit.html.erb
<%= form_with(model: @student, url: [@teacher, @student], local: true) do |f| %>
    <p>Name: <%= f.text_field :name %></p>
    <p>Bio: <%= f.text_area :bio %></p>
    <p>Strengths: <%= f.text_field :strengths %></p>
    <p>Weaknesses: <%= f.text_field :weaknesses %></p>
    <p>Interests: <%= f.text_field :interests %></p>
    <p>Grades: <%= f.text_field :grades %></p>
    <p>Courses: <%= f.collection_check_boxes :course_ids, @teacher.courses, :id, :title %></p>
    <%= f.submit "Update" %>
<% end %>


app/views/students/enroll.html.erb
<h3>Name: <%= link_to @student.name.capitalize, teacher_student_path(@student) %></h3>
<p>Teacher: <%= link_to @student.teacher.name, teacher_path(@teacher) %></p>

<%= form_with model: @course do |f| %>
  <%= f.collection_select(:title, @courses, :id, :title) %>
    <%= f.hidden_field :teacher_id, :value => @teacher.id %>
    <%= f.hidden_field :student_id, :value => @student.id %>
  <%= f.submit "Assign Course" %>
<% end %>

<% if @warning == true %>
  <p class="warning"> Student is already in enrolled in this class!</p>
<% end %>





app/views/students/index.html.erb
<h3>Students</h3>

<p><% @students.each do |s| %>
    <p><b><%= link_to s.name, '/teachers/' + @teacher.id.to_s + '/students/' + s.id.to_s  %></b> - <% s.courses.each do |c| %>
            <%= c.title %> &nbsp
        <% end %>
    <% end %>
    </p>

<p><%= link_to "Create a New Student", new_teacher_student_path(@teacher) %></p>

app/views/students/new.html.erb
<h3>Create a Student</h3>

<% if @student.errors.any? %>
  <div id="error_explanation">
    <p class="warning"><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved: </p>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li class="warning"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @teacher.courses.count != 0 %>
  
    <%= form_with(model: @student, url: [@teacher, @student], local: true) do |f| %>
        <p>Name: <%= f.text_field :name %></p>
        <p>Bio: <%= f.text_area :bio %></p>
        <p>Strengths: <%= f.text_field :strengths %></p>
        <p>Weaknesses: <%= f.text_field :weaknesses %></p>
        <p>Interests: <%= f.text_field :interests %></p>
        <p>Grades: <%= f.text_field :grades %></p>
        <p>Parent Name: <%= f.text_field :parent_name %></p>
        <p>Parent Phone: <%= f.text_field :parent_phone %></p>
        <p>Parent Email: <%= f.text_field :parent_email %></p>
        <p>Courses: <%= f.collection_check_boxes :course_ids, @teacher.courses, :id, :title %></p>
        <p><%= f.submit "Submit" %></p>
    <% end %>

<% else %>

    <%= form_with(model: @student, url: [@teacher, @student], local: true) do |f| %>
        <p>Name: <%= f.text_field :name %></p>
        <p>Bio: <%= f.text_area :bio %></p>
        <p>Strengths: <%= f.text_field :strengths %></p>
        <p>Weaknesses: <%= f.text_field :weaknesses %></p>
        <p>Interests: <%= f.text_field :interests %></p>
        <p>Grades: <%= f.text_field :grades %></p>
        <p>Parent Name: <%= f.text_field :parent_name %></p>
        <p>Parent Phone: <%= f.text_field :parent_phone %></p>
        <p>Parent Email: <%= f.text_field :parent_email %></p>
        <p><%= f.submit "Submit" %></p>
    <% end %>

<% end %>

app/views/students/show.html.erb
<h3>Name: <%= @student.name.capitalize %></h3>

    <p>Teacher: <%= link_to @teacher.name, teacher_path(@teacher) %></p>
    <p>Bio: <%= @student.bio %></p>
    <p>Strengths: <%= @student.strengths %></p>
    <p>Weaknesses: <%= @student.weaknesses %></p>
    <p>Interests: <%= @student.interests %></p>
    <p>Grades: <%= @student.grades %></p>
    <%if @student.parent %>
        <p>Parent Name: <%= link_to @student.parent.name, parent_path(@student.parent) %></p>
    <% else %>
        
    <% end %>

<% if @student.courses.count != 0 %> 

<h3>Courses: </h3>
    <ul>
        <% @student.courses.each do |c| %>   
            <li><%= link_to c.title, course_path(c) %></li>
        <% end %>
    </ul>

<% end %>


<p><%= link_to "Edit", edit_teacher_student_path(@teacher, @student) %> &nbsp<%= link_to "Delete", teacher_student_path(@teacher, @student), method: :delete %> </p>




