config/routes.rb
Rails.application.routes.draw do
  
  resources :conferences
  resources :parents
  resources :teachers, except: [:index] do
    resources :students
  end
  resources :courses

  get '/' => 'welcome#home'
  get '/signup' => 'teachers#new'
  post '/signup' => 'teachers#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/students/:id/enroll' => 'students#enroll', as: 'enroll'
  post '/students/:id/enroll' => 'students#create_enrollment'
  get '/students/:id/unenroll' => 'students#unenroll', as: 'unenroll'
end

app/models/conference.rb
class Conference < ApplicationRecord
    
    belongs_to :teacher
    belongs_to :parent
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController

    layout "logged_in"

        before_action :authenticate
    
        def index
            @teacher = Teacher.find(session[:teacher_id])
        end
    
        def new
            @conference = Conference.new
            @teacher = Teacher.find(session[:teacher_id])
            @parents = @teacher.parents
        end
    
        def create
            @teacher = Teacher.find(session[:teacher_id])
            @parent = Parent.find(params[:conference][:parent_id])
            #@conference = Conference.create(conference_params)
            @conference = Conference.create(
                teacher_id: @teacher.id,
                parent_id: @parent.id,
                date: params[:conference][:date],
                time: params[:conference][:time]
            )
            if @conference.save
                redirect_to conference_path(@conference)
            else
                render :new
            end
        end
    
        def show
            @teacher = Teacher.find(session[:teacher_id])
            @conference = Conference.find(params[:id])
            authorize(@conference)
        end
    
        def edit
            @conference = Conference.find(params[:id])
            authorize(@conference)
        end
    
        def update
            @conference = Conference.find(params[:id])
            authorize(@conference)
            @conference.update(conference_params)
            redirect_to conference_path(@conference)
        end
    
        def destroy
            @conference = conference.find(params[:id])
            @conference.destroy
            redirect_to conferences_path
        end
    
        private
    
        def conference_params
            params.require(:conference).permit(:teacher_id, :parent_id, :date, :time)
        end
        
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/views/conferences/edit.html.erb
<h3>Edit Conference</h3>

<%= form_for @conference do |f| %>
    <p>Parent: <%= @conference.parent.name %></p>
    <p>Date: <%= f.select(:date, ['Oct 20', 'Oct 21', 'Oct 22', 'Oct 23', 'Oct 24']) %></p>
    <p>Time: <%= f.select(:time, ['3 pm', '3:30 pm', '4 pm', '4:30 pm']) %></p>
    <%= f.submit %>
<% end %>



app/views/conferences/index.html.erb
<h3>Conferences</h3> 

<ul>
    <% @teacher.conferences.each do |c| %>
        <% if c.parent %>
            <p><%= link_to c.parent.name, conference_path(c) %> - <%= c.date %> </p>   
        <% end %>  
    <% end %>
</ul>

<%= link_to "Create a conference", new_conference_path %>

app/views/conferences/new.html.erb
<h3>Create a Conference</h3>

<%= form_for @conference do |f| %>
    <p>Parent: <%= f.collection_select :parent_id, @parents, :id, :name %></p>
    <p>Date: <%= f.select(:date, ['Oct 20', 'Oct 21', 'Oct 22', 'Oct 23', 'Oct 24']) %></p>
    <p>Time: <%= f.select(:time, ['3 pm', '3:30 pm', '4 pm', '4:30 pm']) %></p>
    <%= f.submit %>
<% end %>



app/views/conferences/show.html.erb
<h3>Scheduled Conference</h3>

    <p>Teacher: <%= link_to @teacher.name, teacher_path(@teacher) %></p>
    <p>Parent: <%= @conference.parent.name %></p>
    <p>Date: <%= @conference.date %></p>
    <p>Time: <%= @conference.time %></p>

<p><%= link_to "Edit", edit_conference_path(@conference) %> </p>
<p><%#= link_to "Delete", teacher_student_path(@teacher, @student), method: :delete %> </p>




