config/routes.rb
Rails.application.routes.draw do
  
  resources :conferences
  resources :parents
  resources :teachers, except: [:index] do
    resources :students
  end
  resources :courses

  get '/' => 'welcome#home'
  get '/signup' => 'teachers#new'
  post '/signup' => 'teachers#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/students/:id/enroll' => 'students#enroll', as: 'enroll'
  post '/students/:id/enroll' => 'students#create_enrollment'
  get '/students/:id/unenroll' => 'students#unenroll', as: 'unenroll'
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_secure_password
    validates :password, presence: true
    validates :username, uniqueness: true
    has_many :students
    has_many :courses
    has_many :conferences
    has_many :parents, through: :conferences
    has_many :parents, through: :students
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
layout "logged_in"

    before_action :authenticate, except: [:new, :create]
    
    def index
        @teachers = Teacher.all
    end

    def new
        @teacher = Teacher.new
    end

    def create
        @teacher = Teacher.create(teacher_params) 
        if @teacher.save
            session[:teacher_id] = @teacher.id
            redirect_to teacher_path(@teacher)
        else
            redirect_to '/signup'
        end
    end

    def show
        @teacher = Teacher.find(params[:id])
        @students = Student.where("teacher_id= ?", @teacher.id)
        if @teacher.id != session[:teacher_id]
            redirect_to '/403.html'
        end
        #@courses = Course.where("teacher_id= ?", @teacher.id)
        #flash[:warning] = "You are not authorized motherfucker!"
    end

    def edit
        @teacher = Teacher.find(params[:id])
    end

    def update
        @teacher = Teacher.find(params[:id])
        @teacher.update(teacher_params)
        redirect_to teacher_path(@teacher)
    end

    def destroy
        @teacher = Teacher.find(params[:id])
        @teacher.destroy
        redirect_to '/login'
    end

    private

    def teacher_params
        params.require(:teacher).permit(:name, :username, :password, :password_confirmation)
    end

end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_signup.html.erb
<%= form_for user do |f| %>
    <p>Name: <%= f.text_field :name %></p>
    <p>Username: <%= f.text_field :username %></p>
    <p>Password: <%= f.password_field :password %></p>
    <p>Password Confirmation: <%= f.password_field :password_confirmation %></p>
    <p><%= f.submit "Submit" %></p>
<% end %>




app/views/teachers/edit.html.erb
<%= form_for @teacher do |f| %>
    
    <p><%= f.label 'Name: ' %><%= f.text_field :name %></p>
    <p><%= f.label 'Username: ' %><%= f.text_field :username %></p>
    <p><%= f.label 'Password: ' %><%= f.password_field :password %></p>
    <p><%= f.label 'Password Confirmation: ' %><%= f.password_field :password_confirmation %></p>
    <%= f.submit "Update" %>

<% end %>

app/views/teachers/new.html.erb
<h2>Sign Up</h2>
<%= render partial: "signup", locals: {user: @teacher} %>

app/views/teachers/show.html.erb
<h2>Hi <%= @teacher.name %>!</h2>
<p>Username: <%= @teacher.username %></p>

<% if @teacher.courses.count == 0 %>
    <p><%= link_to "Create a New Course", new_course_path %></p>
<% else %> 
    <p>Number of <%= link_to "Courses:", courses_path %> <%= @teacher.courses.count %></p> 
    <% if @teacher.students.count == 0  %>
        <p><%= link_to "Create a New Student", new_teacher_student_path(@teacher) %></p>
    <% else %>
        <p>Number of <%= link_to "Students:", teacher_students_path(@teacher) %> <%= @teacher.students.count %></p> 
        <% if @teacher.courses.count == 0 %>
            <p><%= link_to "Create a Conference", new_conference_path %></p>
        <% else %>
            <p>Number of <%= link_to "Conferences:", conferences_path %> <%= @teacher.conferences.count %></p> 
        <% end %>
    <% end %>
<% end %>

<p><%= link_to "Edit", edit_teacher_path(@teacher) %> &nbsp <%= link_to "Delete", teacher_path(@teacher), method: :delete %> </p>






