config/routes.rb
Rails.application.routes.draw do
  
  resources :conferences
  resources :parents
  resources :teachers, except: [:index] do
    resources :students
  end
  resources :courses

  get '/' => 'welcome#home'
  get '/signup' => 'teachers#new'
  post '/signup' => 'teachers#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: 'logout'
  get '/auth/facebook/callback' => 'sessions#facebook_create'
  get '/students/:id/enroll' => 'students#enroll', as: 'enroll'
  post '/students/:id/enroll' => 'students#create_enrollment'
  get '/students/:id/unenroll' => 'students#unenroll', as: 'unenroll'
end

app/models/parent.rb
class Parent < ApplicationRecord
    validates :name, presence: true
    has_one :student, dependent: :nullify 
    has_many :conferences
    has_many :teachers, through: :conferences
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController

layout "logged_in"

    before_action :authenticate

    def index
        @parents = Teacher.find(session[:teacher_id]).parents
    end

    def show
        @parent = Parent.find(params[:id])
        parent_authorize(@parent)          
    end

    def edit
        @parent = Parent.find(params[:id])
        parent_authorize(@parent)          
    end
  
    def update
        @parent = Parent.find(params[:id])
        parent_authorize(@parent)          
        @parent.update(parent_params)
        render :show
    end

    def destroy
        @parent = Parent.find(params[:id])
        @parent.destroy
        redirect_to parents_path
    end

    private
    
    def parent_params
        params.require(:parent).permit(:name, :phone, :email)
    end

    # def current_user
    #     Teacher.find_by(id: session[:teacher_id])
    # end

    def owns_parent?(parent)
        parent.student.teacher == current_user
    end

    def parent_authorize(parent)
        if !owns_parent?(parent)
            redirect_to '/403.html'
        end
    end

end

app/views/parents/edit.html.erb
<h3> Parent Update </h3>
<%= form_for @parent do |f| %>
        <p>Parent Name: <%= f.text_field :name %></p>
        <p>Parent Phone: <%= f.text_field :phone %></p>
        <p>Parent Email: <%= f.text_field :email %></p>
    <%= f.submit "Update" %>
<% end %>

app/views/parents/index.html.erb
<h3> Parents </h3>
<% @parents.each do |p| %>
    <%= link_to p.name, parent_path(p) %><br>
<% end %> 

app/views/parents/show.html.erb
<h3> Parent Name: <%= @parent.name %> </h3>
<p>Student: <%= @parent.student.name %></p>
<p>Phone: <%= @parent.phone %></p>
<p>Email: <%= @parent.email %></p>

<p><%= link_to "Edit", edit_parent_path(@parent) %> </p>
